import logging
from typing import List, Optional
from dataclasses import dataclass
from datetime import datetime

from config import settings

logger = logging.getLogger(__name__)


@dataclass
class CommitInfo:
    sha: str
    message: str
    author: str
    timestamp: str
    files_changed: List[str]
    url: str


def _get_github_client():
    try:
        from github import Github
        return Github(settings.GITHUB_TOKEN)
    except Exception as e:
        logger.error(f"Failed to init GitHub client: {e}")
        return None


async def get_recent_commits(repo_name: str, limit: int = 10) -> List[CommitInfo]:
    """Fetch recent commits from main/master branch."""
    gh = _get_github_client()
    if not gh:
        return _mock_commits()

    try:
        repo = gh.get_repo(repo_name)
        commits = list(repo.get_commits()[:limit])
        result = []
        for c in commits:
            files = [f.filename for f in c.files] if c.files else []
            result.append(CommitInfo(
                sha=c.sha,
                message=c.commit.message,
                author=c.commit.author.name,
                timestamp=c.commit.author.date.isoformat(),
                files_changed=files,
                url=c.html_url,
            ))
        return result
    except Exception as e:
        logger.warning(f"Failed to fetch commits for {repo_name}: {e}")
        return _mock_commits()


async def get_commit_diff(repo_name: str, sha: str) -> str:
    """Fetch the diff for a specific commit (truncated to 3000 chars)."""
    gh = _get_github_client()
    if not gh:
        return _mock_diff(sha)

    try:
        repo = gh.get_repo(repo_name)
        commit = repo.get_commit(sha)
        diff_parts = []
        for f in commit.files:
            diff_parts.append(f"--- {f.filename}")
            if f.patch:
                diff_parts.append(f.patch)
        full_diff = "\n".join(diff_parts)
        return full_diff[:3000]
    except Exception as e:
        logger.warning(f"Failed to fetch diff for {sha}: {e}")
        return _mock_diff(sha)


async def create_revert_pr(
    repo_name: str,
    commit_sha: str,
    incident_id: str,
    reason: str,
    confidence: int = 0,
) -> Optional[str]:
    """Create a revert branch and open a PR against main."""
    gh = _get_github_client()
    if not gh:
        return f"https://github.com/{repo_name}/pull/47 (mock — GitHub not connected)"

    try:
        repo = gh.get_repo(repo_name)
        short_sha = commit_sha[:7]
        short_incident = incident_id[:8]
        branch_name = f"resolvo/revert-{short_sha}-{short_incident}"

        # Get the default branch HEAD
        default_branch = repo.default_branch
        main_ref = repo.get_git_ref(f"heads/{default_branch}")
        main_sha = main_ref.object.sha

        # Create a new branch from main
        repo.create_git_ref(ref=f"refs/heads/{branch_name}", sha=main_sha)

        # Get the commit to revert and its parent
        target_commit = repo.get_commit(commit_sha)
        parent_sha = target_commit.parents[0].sha if target_commit.parents else main_sha

        # Revert: update each file changed in the target commit back to parent's version
        files_reverted = []
        for f in target_commit.files:
            try:
                # Get the file content at the parent commit
                parent_content = repo.get_contents(f.filename, ref=parent_sha)
                current_file = repo.get_contents(f.filename, ref=branch_name)
                repo.update_file(
                    path=f.filename,
                    message=f"revert: {f.filename} to pre-{short_sha} state",
                    content=parent_content.decoded_content,
                    sha=current_file.sha,
                    branch=branch_name,
                )
                files_reverted.append(f.filename)
            except Exception as fe:
                logger.warning(f"Could not revert file {f.filename}: {fe}")

        # Open the PR
        pr_title = f"fix: revert {short_sha} — auto-fix by Resolvo"
        pr_body = f"""## Automated Revert by Resolvo

**Incident ID:** `{incident_id}`
**Root Cause:** {reason}
**CGEV Confidence Score:** {confidence}/100
**Commit Reverted:** `{commit_sha}`
**Author:** {target_commit.commit.author.name}

### What happened
{reason}

### Files reverted
{chr(10).join(f'- `{f}`' for f in files_reverted) or '- (no files reverted — manual review required)'}

### Action required
Review this PR and merge to restore service. Resolvo has already notified the team via Slack.

---
*Auto-generated by [Resolvo](https://resolvo.ai) — AI On-Call Engineer*
"""
        pr = repo.create_pull(
            title=pr_title,
            body=pr_body,
            head=branch_name,
            base=default_branch,
        )
        logger.info(f"Created revert PR: {pr.html_url}")
        return pr.html_url

    except Exception as e:
        logger.error(f"Failed to create revert PR: {e}")
        return f"https://github.com/{repo_name}/pull/99 (mock — error: {str(e)[:80]})"


# ── Mock data fallbacks ──────────────────────────────────────────────────────

def _mock_commits() -> List[CommitInfo]:
    return [
        CommitInfo(
            sha="abc1234def567890abc1234def567890abc12345",
            message="refactor: remove null check in PaymentHandler.process() for performance",
            author="sarah",
            timestamp="2026-04-25T01:00:00Z",
            files_changed=["src/payments/PaymentHandler.py", "tests/test_payment.py"],
            url="https://github.com/example/repo/commit/abc1234",
        ),
        CommitInfo(
            sha="bcd2345ef678901bcd2345ef678901bcd23456",
            message="feat: add new payment provider integration",
            author="mike",
            timestamp="2026-04-24T22:00:00Z",
            files_changed=["src/payments/providers/stripe.py"],
            url="https://github.com/example/repo/commit/bcd2345",
        ),
        CommitInfo(
            sha="cde3456fg789012cde3456fg789012cde34567",
            message="chore: update dependencies",
            author="alex",
            timestamp="2026-04-24T18:00:00Z",
            files_changed=["requirements.txt"],
            url="https://github.com/example/repo/commit/cde3456",
        ),
    ]


def _mock_diff(sha: str) -> str:
    short = sha[:7]
    return f"""diff --git a/src/payments/PaymentHandler.py b/src/payments/PaymentHandler.py
index 1234567..abcdefg 100644
--- a/src/payments/PaymentHandler.py
+++ b/src/payments/PaymentHandler.py
@@ -44,10 +44,7 @@ class PaymentHandler:
     def process(self, payment_data):
-        if payment_data is None:
-            raise ValueError("payment_data cannot be None")
-        if payment_data.get('amount') is None:
-            raise ValueError("amount is required")
         amount = payment_data['amount']  # NullPointerException risk
         currency = payment_data['currency']
         return self._charge(amount, currency)"""
