"""Auto post-mortem generator using Claude API."""

import logging
from datetime import datetime
from typing import Optional

from agent.confidence import get_anthropic_client

logger = logging.getLogger(__name__)


async def generate_postmortem(incident: dict) -> str:
    """
    Generate a structured post-mortem document from incident data.
    Returns a markdown string ready for Google Docs / Notion / Confluence.
    """
    service = incident.get("service", "unknown")
    title = incident.get("title", "Unknown incident")
    root_cause = incident.get("root_cause", "Not determined")
    remediation_action = incident.get("remediation_action", "manual intervention")
    confidence_score = incident.get("confidence_score", 0)
    pr_url = incident.get("pr_url", "")
    status = incident.get("status", "UNKNOWN")

    started_at = _parse_dt(incident.get("started_at"))
    resolved_at = _parse_dt(incident.get("resolved_at"))
    date_str = started_at.strftime("%Y-%m-%d") if started_at else datetime.utcnow().strftime("%Y-%m-%d")

    duration_minutes = 0
    if started_at and resolved_at:
        duration_minutes = int((resolved_at - started_at).total_seconds() / 60)

    cost_estimate = incident.get("cost_estimate", 0) or 0

    # Build timeline from reasoning trace
    trace = incident.get("reasoning_trace") or []
    timeline_lines = []
    for step in trace:
        if isinstance(step, dict):
            ts = step.get("timestamp", "")
            text = step.get("step", "")
            if text:
                timeline_lines.append(f"- `{ts}` — {text}")
        elif isinstance(step, str):
            timeline_lines.append(f"- {step}")

    timeline_text = "\n".join(timeline_lines) if timeline_lines else "- Timeline not available"

    prompt = f"""Generate a detailed incident post-mortem in markdown format for the following incident.
Follow this exact template structure and fill in all sections with specific, actionable content.

INCIDENT DATA:
- Service: {service}
- Title: {title}
- Date: {date_str}
- Root cause: {root_cause}
- Status: {status}
- Auto-resolved: {"Yes" if status == "RESOLVED" else "No (escalated)"}
- Time to resolve: {duration_minutes} minutes
- Confidence score: {confidence_score}/100
- Fix applied: {remediation_action}
- PR created: {pr_url if pr_url else "None"}
- Estimated cost impact: ${cost_estimate:,.2f}

TIMELINE:
{timeline_text}

Generate the post-mortem now:

## Incident Post-Mortem — {service} — {date_str}

### Summary
[Write 2-3 sentences summarizing what happened, impact, and how it was resolved]

### Timeline
[Use the timeline data above, formatted as bullet points with times]

### Root Cause
[Detailed root cause analysis]

### Contributing Factors
[2-4 factors that made this incident possible]

### Resolution
[What was done to resolve it, including any PRs or manual steps]

### Action Items
[Exactly 5 specific, actionable prevention items with owners and due dates]

### Metrics
- Time to detect: [X] min
- Time to resolve: {duration_minutes} min
- Estimated impact: ${cost_estimate:,.2f}
- CGEV Confidence Score: {confidence_score}/100
- Auto-resolved by Resolvo: {"Yes" if status == "RESOLVED" else "No"}

---
*Generated by Resolvo AI On-Call Engineer*"""

    try:
        client = get_anthropic_client()
        response = client.messages.create(
            model="claude-sonnet-4-5",
            max_tokens=2048,
            messages=[{"role": "user", "content": prompt}],
        )
        postmortem = response.content[0].text.strip()
        logger.info(f"Post-mortem generated for incident {incident.get('id', '?')}")
        return postmortem
    except Exception as e:
        logger.error(f"Failed to generate post-mortem: {e}")
        return _fallback_postmortem(incident, date_str, duration_minutes, timeline_text)


def _fallback_postmortem(incident: dict, date_str: str, duration_minutes: int, timeline_text: str) -> str:
    service = incident.get("service", "unknown")
    root_cause = incident.get("root_cause", "Not determined")
    cost_estimate = incident.get("cost_estimate", 0) or 0
    confidence_score = incident.get("confidence_score", 0)
    status = incident.get("status", "UNKNOWN")
    return f"""## Incident Post-Mortem — {service} — {date_str}

### Summary
An incident occurred in the {service} service. Root cause: {root_cause}. 
Status: {status}. Duration: {duration_minutes} minutes.

### Timeline
{timeline_text}

### Root Cause
{root_cause}

### Contributing Factors
- Insufficient safeguards in deployment pipeline
- Missing automated regression tests for this code path
- Monitoring alert threshold may need tuning

### Resolution
{"Resolved automatically by Resolvo." if status == "RESOLVED" else "Escalated to human on-call engineer for manual intervention."}

### Action Items
1. Add regression tests for the affected code path (owner: engineering team, due: 1 week)
2. Review deployment checklist to prevent similar regressions (owner: team lead, due: 2 weeks)
3. Add pre-deployment smoke tests (owner: DevOps, due: 2 weeks)
4. Tune monitoring alert thresholds (owner: SRE, due: 1 week)
5. Document runbook for this failure mode (owner: on-call rotation, due: 1 week)

### Metrics
- Time to detect: < 1 min (automated)
- Time to resolve: {duration_minutes} min
- Estimated impact: ${cost_estimate:,.2f}
- CGEV Confidence Score: {confidence_score}/100
- Auto-resolved by Resolvo: {"Yes" if status == "RESOLVED" else "No"}

---
*Generated by Resolvo AI On-Call Engineer*"""


def _parse_dt(value) -> Optional[datetime]:
    if not value:
        return None
    if isinstance(value, datetime):
        return value
    try:
        return datetime.fromisoformat(str(value).replace("Z", "+00:00"))
    except Exception:
        return None
